//! `flaketide init` — write a starter flaketide.toml in the repo root.

use std::fs;
use std::path::Path;

use clap::Args;

use crate::cli::FrameworkArg;
use crate::domain::Framework;
use crate::error::{FlaketideError, Result};
use crate::util::paths::{ensure_flaketide_dir, find_repo_root};

#[derive(Debug, Args)]
pub struct InitArgs {
    /// Framework to pre-fill in the config. Default: auto-detect from repo files.
    #[arg(long, value_enum)]
    pub framework: Option<FrameworkArg>,
    /// Overwrite existing flaketide.toml.
    #[arg(long)]
    pub force: bool,
}

pub async fn run(args: InitArgs, config: Option<&Path>) -> Result<i32> {
    let cwd = std::env::current_dir()?;
    let root = config
        .and_then(|p| p.parent().map(|p| p.to_path_buf()))
        .or_else(|| find_repo_root(&cwd))
        .unwrap_or(cwd);

    let toml_path = root.join("flaketide.toml");
    // (M4) Eliminate the TOCTOU race between "exists?" and "write".
    // Without --force, use create_new(true) which atomically fails if the
    // file (or a symlink that resolves to one) already exists.
    if !args.force {
        match std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&toml_path)
        {
            Ok(_handle) => { /* sentinel created — fs::write below rewrites content */ }
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
                return Err(FlaketideError::Config(format!(
                    "{} already exists; pass --force to overwrite",
                    toml_path.display()
                )));
            }
            Err(e) => return Err(FlaketideError::Io(e)),
        }
    }

    let framework: Option<Framework> = args.framework.map(Into::into).or_else(|| detect_framework(&root));
    let fw_str = framework.map(|f| f.as_str()).unwrap_or("# auto-detect at run-time");

    let content = format!(
        r#"# flaketide configuration generated by `flaketide init`.
framework = "{fw_str}"
runs = 10
parallel = 1
db_path = ".flaketide/history.db"

[thresholds]
flake_prob_min = 0.05
hdi_width_max = 0.30
severity_alert = 0.50

[quarantine]
max_age_days = 30
max_count = 25

[ai]
model = "claude-opus-4-7"
max_log_excerpt_chars = 12000

[github]
issue_title = "Flaky tests - flaketide report"
issue_labels = ["flaky-test", "automated"]
"#
    );

    fs::write(&toml_path, content)?;
    ensure_flaketide_dir(&root)?;

    // Add `.flaketide/` to .gitignore if a .gitignore exists.
    let gitignore = root.join(".gitignore");
    if gitignore.exists() {
        let current = fs::read_to_string(&gitignore)?;
        if !current.lines().any(|l| l.trim() == ".flaketide" || l.trim() == ".flaketide/") {
            let mut updated = current;
            if !updated.ends_with('\n') {
                updated.push('\n');
            }
            updated.push_str(".flaketide/\n");
            fs::write(&gitignore, updated)?;
        }
    }

    eprintln!("wrote {}", toml_path.display());
    eprintln!("created {}", root.join(".flaketide").display());
    eprintln!("next: flaketide run -- <your test command>");
    Ok(0)
}

/// Heuristic framework detection from common project files.
fn detect_framework(root: &Path) -> Option<Framework> {
    let exists = |p: &str| root.join(p).exists();
    if exists("Cargo.toml") {
        return Some(Framework::Cargo);
    }
    if exists("go.mod") {
        return Some(Framework::GoTest);
    }
    if exists("vitest.config.ts") || exists("vitest.config.js") || exists("vite.config.ts") {
        return Some(Framework::Vitest);
    }
    if exists("package.json") {
        let txt = std::fs::read_to_string(root.join("package.json")).unwrap_or_default();
        if txt.contains("\"vitest\"") {
            return Some(Framework::Vitest);
        }
        if txt.contains("\"jest\"") {
            return Some(Framework::Jest);
        }
    }
    if exists("pyproject.toml") || exists("pytest.ini") || exists("setup.cfg") {
        return Some(Framework::PytestJunit);
    }
    if exists("pom.xml") || exists("build.gradle") || exists("build.gradle.kts") {
        return Some(Framework::JunitXml);
    }
    None
}
